### ISSUE TITLE
HA 114.2  error log

### ISSUE THREAD

**Issue by jyz0501** [Zrincet/IHC8342B_query#1]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 192, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 474, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 308, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/IHC8342B_query/sensor.py", line 213, in device_state_attributes
    **ATTR_PRICE: "%.2f元" % round(self._state * self._price, 2)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'**

Something wrong in IHC8342B sensor. 'NoneType' object is not subscriptable

**Comment by jyz0501** [comment]
> 问了一下鸿雁客服，回复是 技术正在处理 ，应该是官方的BUG问题，等待官方修复

好的
